# Generated by Django 5.1 on 2025-03-20 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('car_make', models.CharField(max_length=100)),
                ('car_year', models.IntegerField()),
                ('price_per_day', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='car_images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_renter', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_cost', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.car_model')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.user')),
            ],
        ),
        migrations.CreateModel(
            name='payment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.booking')),
            ],
        ),
        migrations.AddField(
            model_name='car_model',
            name='car_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.user'),
        ),
    ]
