# Generated by Django 5.1.7 on 2025-03-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car_Model',
            new_name='CarModel',
        ),
        migrations.RenameModel(
            old_name='payment_model',
            new_name='PaymentModel',
        ),
    ]
